import {
  type AuthoredCatalogs,
  applyQueuedTranslations,
  createCompleteCatalogs,
  type PlatformLocale,
} from "@ledgame/platform-shared-ui";
import persistedTranslations from "../../../i18n/translations.json";

export const MEMBER_ADMIN_LOCALE_STORAGE_KEY = "ledgame.member-admin.locale";

export const memberAdminBaseCatalog = {
  language: "Language",
  chooseLanguage: "Choose language",
  close: "Close",
  openNavigation: "Open navigation",
  closeNavigation: "Close navigation",
  mainFunctions: "Main functions",
  navWristbands: "Wristbands",
  navOverview: "Overview",
  navRooms: "Rooms",
  navMembers: "Members",
  navRecords: "Records & data",
  navRanking: "Leaderboard",
  navSettings: "Settings",
  descWristbands: "Charge, activate, inspect and recycle wristbands",
  descOverview: "Today's key store metrics and live status",
  descRooms: "Monitor room progress, scores and device status",
  descMembers: "Search and maintain member profiles and balances",
  descRecords: "Review wristband bindings, charges, plays and member records",
  descRanking: "Preview daily, monthly and yearly rankings",
  descSettings: "Configure wristband rules and system options",
  points: "Points",
  rank: "Rank",
  rawScore: "Raw score",
  memberPoints: "Member points",
  statusReason: "Status / reason",
  startEndTime: "Start / end time",
  runtimeEyebrow: "Windows local service",
  runtimeTitle: "Local service and LAN connection",
  runtimePort: "Service port",
  runtimeDatabase: "SQLite database",
  runtimeLog: "Service log",
  runtimeLanAddresses: "Addresses for other terminals",
  runtimeNoLanAddress: "No non-loopback IPv4 address found",
  runtimeRefresh: "Refresh status",
  runtimeRetry: "Retry startup",
  runtimeRestart: "Save port and restart service",
  leaderboardLoading: "Loading the real leaderboard",
  leaderboardLoadingHint: "Please wait…",
  leaderboardError: "Leaderboard could not be loaded",
  leaderboardRetry: "Retry",
  leaderboardEmptyTitle: "No settled points in this period",
  leaderboardEmptyBody: "Members appear here after a game completes and settles successfully.",
  memberDeleteDangerTitle: "Danger zone",
  memberDeleteDangerBody: "For removing manual test members only. The phone number can be registered again after deletion, while old wristband and game history is retained.",
  memberDeleteAction: "Delete member",
  memberDeleteConfirmTitle: "Delete this member?",
  memberDeleteModalDescription: "This removes the active member profile.",
  memberDeleteConsequences: "The phone number can be registered as a new member with zero points. Old wristband and game history is retained.",
  chargeStartDescription: "Click the button to start accepting reader input. The database is not changed until the final confirmation.",
  chargeStart: "Charge wristband",
  chargeScanTitle: "Scan wristband",
  chargeConfirmTitle: "Confirm charge details",
  chargeScanDescription: "Hold the physical wristband to the reader. It will enter the UID and press Enter automatically.",
  chargeConfirmDescription: "Verify the wristband and purchased duration. The database is only written after confirmation.",
  chargeChecking: "Checking wristband status…",
  chargeWaiting: "Waiting for wristband",
  chargeCaptureHint: "Reader input is accepted only while this prompt is visible",
  chargeScannedUid: "Scanned wristband UID",
  chargeConfirm: "Confirm charge",
  dashboardEyebrow: "Store operations",
  dashboardRoomPrefix: "There are currently",
  dashboardPlayingRooms: "rooms in play",
  dashboardOnlineRooms: "rooms online",
  dashboardRefresh: "Refresh data",
  dashboardRefreshing: "Refreshing…",
  dashboardError: "Some overview data could not be loaded. You can retry manually.",
  dashboardCoreStats: "Today's key metrics",
  dashboardTotalMembers: "Total members",
  dashboardActiveMembers: "Active member profiles",
  dashboardNewMembers: "New today",
  dashboardToday: "Store-local day",
  dashboardChargedWristbands: "Charges today",
  dashboardSuccessfulCharges: "Successful charge transactions",
  dashboardRevenue: "Revenue today",
  dashboardRevenueRule: "CNY 1 per charged minute",
  dashboardRoomStatus: "Live room status",
  dashboardViewAll: "View all",
  dashboardInGame: "In game",
  dashboardWaiting: "Waiting for players",
  dashboardOffline: "Offline",
  dashboardIdle: "Idle",
  dashboardQueue: "Queue",
  dashboardNoRoomsTitle: "No game terminal is connected",
  dashboardNoRoomsBody: "A room appears here after its game terminal connects.",
  roomGameRemaining: "Global game time remaining",
  roomUnlimited: "Unlimited",
  wristbandFlowDescription: "Charge at the counter first; the customer then finds or creates a member and binds the wristband at the kiosk. Timing starts on the first scan at a game terminal.",
  loginTitle: "Member administration login",
  loginDescription: "Enter an enabled operator account to continue.",
  loginUsername: "Username",
  loginPassword: "Password",
  loginAction: "Log in",
  loginSubmitting: "Logging in…",
  loginFactoryHelp: "If the factory administrator password is lost, contact the manufacturer for reinstall or factory recovery.",
  logout: "Log out",
  brandLedGame: "LED GAME",
  brandMemberAdmin: "MEMBER ADMIN",
  loginEyebrow: "OPERATOR ACCESS",
  operatorAccountsEyebrow: "OPERATOR ACCOUNTS",
  operatorAccountsTitle: "Operator accounts",
  operatorAccountsDescription: "Create and disable secondary store operator accounts. Accounts cannot be deleted.",
  operatorAccountsCreate: "New operator",
  operatorAccountColumnAccount: "Account",
  operatorAccountColumnDisplayName: "Display name",
  operatorAccountColumnType: "Type",
  operatorAccountColumnStatus: "Status",
  operatorAccountColumnActions: "Actions",
  operatorAccountEdit: "Edit",
  operatorAccountResetPassword: "Reset password",
  backupWarningDetail: "View details",
  maintenanceOnlyTitle: "Factory maintenance only",
  maintenanceOnlyBody: "Log out and use the factory account to resolve the database backup conflict.",
  importModalTitle: "Confirm database import",
  importOverwriteTitle: "The current database will be overwritten",
  importOverwriteBody: "The local service will stop and preserve a pre-import copy. Import is rejected while games or queues are active.",
  importAccountWarning: "After import, sign in with the factory account stored in this backup.",
  importFactoryUsername: "Factory account after import",
  importMemberCount: "Members in candidate",
  keepCurrentAction: "Keep current database",
  keepCurrentTitle: "Keep the current database?",
  keepCurrentBody: "The conflicting backup will be preserved in quarantine, then a new backup will be created from the current database.",
};

export type MemberAdminMessageKey = keyof typeof memberAdminBaseCatalog;

type Copy = Partial<Record<MemberAdminMessageKey, string>>;

const navigation = (
  language: string,
  chooseLanguage: string,
  values: [string, string, string, string, string, string, string],
): Copy => ({
  language,
  chooseLanguage,
  navWristbands: values[0],
  navOverview: values[1],
  navRooms: values[2],
  navMembers: values[3],
  navRecords: values[4],
  navRanking: values[5],
  navSettings: values[6],
});

export const memberAdminAuthoredCatalogs = {
  "zh-CN": {
    roomGameRemaining: "全局游戏剩余",
    roomUnlimited: "无限",
    language: "语言",
    chooseLanguage: "选择语言",
    close: "关闭",
    openNavigation: "打开导航",
    closeNavigation: "关闭导航",
    mainFunctions: "管理中心",
    navWristbands: "手环管理",
    navOverview: "运营总览",
    navRooms: "房间管理",
    navMembers: "会员管理",
    navRecords: "记录与数据",
    navRanking: "积分排行",
    navSettings: "系统设置",
    descWristbands: "完成手环充时、激活、查询与回收",
    descOverview: "门店今天的关键数据与实时状态",
    descRooms: "掌握房间进度、积分与设备状态",
    descMembers: "查询和维护会员资料与余额",
    descRecords: "集中查看手环绑定、充时交易、游玩与会员记录",
    descRanking: "查看日、月、年度积分排行榜",
    descSettings: "配置手环规则与系统选项",
    points: "积分",
    rank: "排名",
    rawScore: "原始分数",
    memberPoints: "会员积分",
    statusReason: "状态 / 原因",
    startEndTime: "开始 / 结束时间",
    runtimeEyebrow: "Windows 本机服务",
    runtimeTitle: "本机服务与局域网连接",
    runtimePort: "服务端口",
    runtimeDatabase: "SQLite 数据库",
    runtimeLog: "服务日志",
    runtimeLanAddresses: "其他终端可填写的地址",
    runtimeNoLanAddress: "未发现非回环 IPv4 地址",
    runtimeRefresh: "刷新状态",
    runtimeRetry: "重试启动",
    runtimeRestart: "保存端口并重启服务",
    leaderboardLoading: "正在读取真实积分榜",
    leaderboardLoadingHint: "请稍候…",
    leaderboardError: "排行榜加载失败",
    leaderboardRetry: "重试",
    leaderboardEmptyTitle: "当前周期暂无已结算积分",
    leaderboardEmptyBody: "会员完成游戏并正常结算后会出现在这里。",
    memberDeleteDangerTitle: "危险操作",
    memberDeleteDangerBody: "仅用于清理手动测试会员。删除后手机号可以重新注册，旧的手环与游戏历史记录仍会保留。",
    memberDeleteAction: "删除会员",
    memberDeleteConfirmTitle: "确认删除会员？",
    memberDeleteModalDescription: "这是会员资料清理操作。",
    memberDeleteConsequences: "删除后该手机号可以重新注册为新的会员，积分从 0 开始；旧会员的手环与游戏历史记录仍会保留。",
    chargeStartDescription: "点击按钮后才会开始接收读卡器输入。刷卡成功前不会修改数据库。",
    chargeStart: "手环充值",
    chargeScanTitle: "请刷手环",
    chargeConfirmTitle: "确认充值信息",
    chargeScanDescription: "把实体手环贴近读卡器，读卡器会自动输入 UID 并发送回车。",
    chargeConfirmDescription: "核对手环和购买时长，确认后才会写入数据库。",
    chargeChecking: "正在检查手环状态…",
    chargeWaiting: "等待刷手环",
    chargeCaptureHint: "仅在此提示显示时接收读卡器输入",
    chargeScannedUid: "已扫描手环 UID",
    chargeConfirm: "确认充值",
    dashboardEyebrow: "门店运营",
    dashboardRoomPrefix: "当前有",
    dashboardPlayingRooms: "个房间正在游戏",
    dashboardOnlineRooms: "个房间在线",
    dashboardRefresh: "刷新数据",
    dashboardRefreshing: "正在刷新…",
    dashboardError: "部分运营数据加载失败，可手动重试。",
    dashboardCoreStats: "今日核心统计",
    dashboardTotalMembers: "总会员数",
    dashboardActiveMembers: "当前有效会员",
    dashboardNewMembers: "今日新增",
    dashboardToday: "按门店自然日统计",
    dashboardChargedWristbands: "今日发卡",
    dashboardSuccessfulCharges: "成功充值次数",
    dashboardRevenue: "今日收款",
    dashboardRevenueRule: "暂按每充值 1 分钟计 1 元",
    dashboardRoomStatus: "房间实时概况",
    dashboardViewAll: "查看全部",
    dashboardInGame: "游戏中",
    dashboardWaiting: "等待玩家刷卡",
    dashboardOffline: "离线",
    dashboardIdle: "空闲",
    dashboardQueue: "排队",
    dashboardNoRoomsTitle: "暂无游戏桌面端连接",
    dashboardNoRoomsBody: "游戏桌面端连接后，真实房间会显示在这里。",
    wristbandFlowDescription: "柜台先完成充时；顾客再到自助端查询或创建会员并绑定手环，首次在游戏设备刷卡后才开始计时。",
    loginTitle: "会员管理端登录",
    loginDescription: "请使用已启用的操作账号进入管理界面。",
    loginUsername: "用户名",
    loginPassword: "密码",
    loginAction: "登录",
    loginSubmitting: "正在登录…",
    loginFactoryHelp: "如果忘记出厂管理员密码，请联系厂家重装或恢复出厂。",
    logout: "退出登录",
    brandLedGame: "LED GAME",
    brandMemberAdmin: "MEMBER ADMIN",
    loginEyebrow: "OPERATOR ACCESS",
    operatorAccountsEyebrow: "OPERATOR ACCOUNTS",
    operatorAccountsTitle: "操作账号",
    backupWarningDetail: "查看详情",
    maintenanceOnlyTitle: "当前仅开放出厂维护",
    maintenanceOnlyBody: "请退出当前账号，并使用出厂账号登录处理数据库备份冲突。",
    importModalTitle: "确认导入数据库",
    importOverwriteTitle: "当前数据库将被覆盖",
    importOverwriteBody: "系统会先停止本机服务并保留导入前副本；有游戏或排队时会拒绝导入。",
    importAccountWarning: "导入后必须使用这份备份中保存的出厂账号和密码重新登录。",
    importFactoryUsername: "导入后出厂账号",
    importMemberCount: "候选会员数量",
    keepCurrentAction: "保留当前数据库",
    keepCurrentTitle: "确认保留当前数据库？",
    keepCurrentBody: "冲突备份会完整保留到隔离目录，然后以当前数据库重新建立正式备份。",
    operatorAccountsDescription: "出厂管理员可创建和停用门店操作员；账号不提供删除。",
    operatorAccountsCreate: "新建操作员",
    operatorAccountColumnAccount: "账号",
    operatorAccountColumnDisplayName: "显示名称",
    operatorAccountColumnType: "类型",
    operatorAccountColumnStatus: "状态",
    operatorAccountColumnActions: "操作",
    operatorAccountEdit: "编辑",
    operatorAccountResetPassword: "重设密码",
  },
  "es-ES": navigation("Idioma", "Elegir idioma", ["Pulseras", "Resumen", "Salas", "Miembros", "Registros y datos", "Clasificación", "Ajustes"]),
  "pt-PT": navigation("Idioma", "Escolher idioma", ["Pulseiras", "Visão geral", "Salas", "Membros", "Registos e dados", "Classificação", "Definições"]),
  "fr-FR": navigation("Langue", "Choisir la langue", ["Bracelets", "Vue d’ensemble", "Salles", "Membres", "Données", "Classement", "Paramètres"]),
  "de-DE": navigation("Sprache", "Sprache wählen", ["Armbänder", "Übersicht", "Räume", "Mitglieder", "Daten", "Rangliste", "Einstellungen"]),
  "pl-PL": navigation("Język", "Wybierz język", ["Opaski", "Przegląd", "Pokoje", "Członkowie", "Dane", "Ranking", "Ustawienia"]),
  "ru-RU": navigation("Язык", "Выберите язык", ["Браслеты", "Обзор", "Комнаты", "Участники", "Данные", "Рейтинг", "Настройки"]),
  "vi-VN": navigation("Ngôn ngữ", "Chọn ngôn ngữ", ["Vòng tay", "Tổng quan", "Phòng", "Thành viên", "Dữ liệu", "Xếp hạng", "Cài đặt"]),
  "it-IT": navigation("Lingua", "Scegli lingua", ["Braccialetti", "Panoramica", "Stanze", "Membri", "Dati", "Classifica", "Impostazioni"]),
  "cs-CZ": navigation("Jazyk", "Zvolit jazyk", ["Náramky", "Přehled", "Místnosti", "Členové", "Data", "Žebříček", "Nastavení"]),
  "ko-KR": navigation("언어", "언어 선택", ["손목밴드", "개요", "게임실", "회원", "기록 및 데이터", "순위", "설정"]),
  "ro-RO": navigation("Limbă", "Alege limba", ["Brățări", "Prezentare", "Camere", "Membri", "Date", "Clasament", "Setări"]),
  "ar-SA": navigation("اللغة", "اختر اللغة", ["الأساور", "نظرة عامة", "الغرف", "الأعضاء", "السجلات والبيانات", "الترتيب", "الإعدادات"]),
} satisfies AuthoredCatalogs<typeof memberAdminBaseCatalog>;

export const memberAdminCatalogs = createCompleteCatalogs(
  memberAdminBaseCatalog,
  applyQueuedTranslations(
    memberAdminBaseCatalog,
    memberAdminAuthoredCatalogs,
    persistedTranslations.applications.memberAdmin.targets,
  ),
);

export function memberAdminMessage(locale: PlatformLocale, key: MemberAdminMessageKey): string {
  return memberAdminCatalogs[locale][key];
}
