import fs from 'node:fs/promises';
import path from 'node:path';

// Includes product logs and caches, not just files generated by the harness.
// Stop with evidence retained; never delete product logs to hide an overflow.
export async function checkEvidenceBudget(directory, { maxBytes = 512 * 1048576, maxFiles = 10000, minFreeBytes = 100 * 1048576 } = {}) {
  const disk = await fs.statfs(directory);
  if (disk.bavail * disk.bsize < minFreeBytes) throw new Error('测试输出盘可用空间不足');
  let bytes = 0; let files = 0; const pending = [directory];
  while (pending.length) {
    const current = pending.pop();
    const entries = await fs.opendir(current);
    for await (const entry of entries) {
      if (++files > maxFiles) throw new Error(`测试目录文件数量超过上限 ${maxFiles}`);
      const file = path.join(current, entry.name);
      if (entry.isSymbolicLink()) throw new Error(`测试目录出现符号链接，拒绝越界采集：${file}`);
      if (entry.isDirectory()) pending.push(file);
      else {
        try { bytes += (await fs.stat(file)).size; }
        catch (error) { if (error.code !== 'ENOENT') throw error; } // Product may rotate its own log.
        if (bytes > maxBytes) throw new Error(`测试目录超过 ${Math.round(maxBytes / 1048576)}MB 证据上限，停止并保留现场`);
      }
    }
  }
  return { bytes, files };
}
