import {
  type AuthoredCatalogs,
  applyQueuedTranslations,
  createCompleteCatalogs,
  type PlatformLocale,
} from "@ledgame/platform-shared-ui";
import persistedTranslations from "../../../i18n/translations.json";

export const REGISTRATION_KIOSK_LOCALE_STORAGE_KEY = "ledgame.registration-kiosk.locale";

export const registrationKioskBaseCatalog = {
  language: "Language",
  chooseLanguage: "Choose language",
  close: "Close",
  rotateTitle: "Rotate your screen",
  rotateBody: "This experience is designed for a landscape kiosk.",
  localService: "Local service",
  serviceDetail: "Reader input + local API",
  titleHome: "Self-Service",
  titleActivate: "Activate Wristband",
  titleConfirm: "Confirm Player",
  titleRegister: "Register Player",
  titleSwipe: "Swipe Wristband",
  titlePlayerInfo: "Player Info",
  stepPhone: "Phone",
  stepProfile: "Profile",
  stepWristband: "Wristband",
  welcome: "Welcome to the player station",
  headlineBefore: "Ready to",
  headlineAccent: "light up",
  headlineAfter: "the game floor?",
  intro: "Activate your wristband in a few simple steps.",
  getStarted: "Get started",
  activateWristband: "Activate wristband",
  activateDetail: "Register player & pair wristband",
  returningPlayer: "Returning player",
  playerInfo: "Player info query",
  playerInfoDetail: "View profile, points, rank and wristband balance",
  touchToBegin: "Touch a card to begin",
  sessionClears: "Session data clears when you return home",
  offlineTitle: "Member Admin connection problem",
  offlineRecovery: "You can restart from the home screen after the connection recovers.",
  operatorEyebrow: "LED GAME · OPERATOR STARTUP",
  operatorTitle: "Registration kiosk startup settings",
  operatorDescription: "This page is for staff only. The customer flow runs in a separate fullscreen window.",
  operatorHost: "Member Admin IP / hostname",
  operatorHostPlaceholder: "For example, 192.168.1.10",
  operatorPort: "Port",
  operatorSave: "Save settings",
  operatorTest: "Test connection",
  operatorLaunch: "Start self-service",
  operatorExitHint: "Double-click the left edge of the customer window and enter the staff password to return to this page.",
  staffExitEyebrow: "STAFF ONLY",
  staffExitTitle: "Close self-service kiosk",
  staffExitDescription: "Enter the staff password to return to the startup settings page.",
  staffExitPasswordLabel: "Staff password",
  staffExitPasswordPlaceholder: "Enter password",
  staffExitCancel: "Cancel",
  staffExitConfirm: "Close kiosk",
  staffExitInvalid: "Incorrect password. Please try again.",
  scanStart: "Start wristband scan",
  scanEyebrow: "WRISTBAND READER",
  scanTitle: "Scan your wristband",
  scanDescription: "Hold the wristband near the reader. This prompt closes automatically after a successful scan.",
  scanSubmittingDescription: "Validating and binding the wristband...",
  scanWaiting: "Waiting for reader input...",
  scanConnecting: "Connecting to Member Admin...",
  scanCancel: "Cancel scan",
  settings: "Settings",
  settingsTitle: "Kiosk settings",
  settingsDescription: "Configure how long each customer flow may remain idle before returning home.",
  settingsSave: "Save settings",
  settingsCancel: "Cancel",
  settingsValidation: "Enter a whole number from 10 to 600 seconds.",
  timeoutActivation: "Activation and registration",
  timeoutWristband: "Wristband scan",
  timeoutSuccess: "Success screen",
  timeoutPlayerInfo: "Player info query",
  countdownRemaining: "Returning home in {seconds}s",
  playerInfoModePhone: "Phone number",
  playerInfoModeWristband: "Wristband",
  playerInfoPhonePlaceholder: "Tap to enter phone number",
  playerInfoWristbandPlaceholder: "Tap to enter wristband UID",
  playerInfoScan: "Scan wristband",
  playerInfoScanTitle: "Scan to find player",
  playerInfoScanDescription: "Hold the wristband near the reader. Only read-only member information will be shown.",
  playerInfoScanCancel: "Cancel lookup",
  playerInfoRecordEyebrow: "PLAYER RECORD · LIVE MEMBER DATA",
  secondsShort: "s",
  offlineMessage: "Member Admin network connection has a problem. Please check the network connection.",
  avatarCameraLabel: "Device camera",
  avatarCameraOptional: "Use a built-in or USB camera. This is optional.",
  avatarCameraEyebrow: "DEVICE CAMERA",
  avatarCameraTitle: "Take a player photo",
  avatarCameraDescription: "The photo is kept temporarily only while this registration is submitted.",
  avatarCameraSelect: "Camera",
  avatarCameraLoading: "Opening camera…",
  avatarCameraGuide: "Place your face inside the frame",
  avatarCameraCancel: "Cancel",
  avatarCameraRetake: "Retake",
  avatarCameraRetry: "Retry camera",
  avatarCameraCapture: "Capture",
  avatarCameraConfirm: "Use photo",
  avatarCameraPhotoReady: "Captured photo",
  avatarCameraPhotoDescription: "Photo ready to submit",
  avatarCameraUnsupported: "This device does not support a camera. Check Windows camera settings.",
  avatarCameraPermissionDenied: "Camera permission was denied. Allow this app to access the camera in Windows privacy settings.",
  avatarCameraNoCamera: "No camera was found. Check the camera connection or driver.",
  avatarCameraBusy: "The camera is in use by another program. Close it and try again.",
  avatarCameraDisconnected: "The camera connection was interrupted. Check the device and try again.",
  avatarCameraCaptureFailed: "Photo processing failed. Retake the photo or use the avatar library.",
};

export type RegistrationKioskMessageKey = keyof typeof registrationKioskBaseCatalog;
type Copy = Partial<Record<RegistrationKioskMessageKey, string>>;

const home = (
  language: string,
  chooseLanguage: string,
  titleHome: string,
  welcome: string,
  headlineBefore: string,
  headlineAccent: string,
  headlineAfter: string,
  intro: string,
  activateWristband: string,
  playerInfo: string,
): Copy => ({ language, chooseLanguage, titleHome, welcome, headlineBefore, headlineAccent, headlineAfter, intro, activateWristband, playerInfo });

export const registrationKioskAuthoredCatalogs = {
  "zh-CN": {
    language: "语言",
    chooseLanguage: "选择语言",
    close: "关闭",
    rotateTitle: "请旋转屏幕",
    rotateBody: "自助注册端需要横屏使用。",
    localService: "本机服务",
    serviceDetail: "读卡器输入 + 本机 API",
    titleHome: "自助服务",
    titleActivate: "激活手环",
    titleConfirm: "确认会员",
    titleRegister: "注册会员",
    titleSwipe: "刷手环",
    titlePlayerInfo: "会员信息",
    stepPhone: "手机号",
    stepProfile: "会员资料",
    stepWristband: "手环",
    welcome: "欢迎使用自助注册端",
    headlineBefore: "准备好",
    headlineAccent: "点亮",
    headlineAfter: "游戏空间了吗？",
    intro: "只需几步即可激活您的手环。",
    getStarted: "开始",
    activateWristband: "激活手环",
    activateDetail: "注册会员并绑定手环",
    returningPlayer: "已有会员",
    playerInfo: "查询会员信息",
    playerInfoDetail: "查看资料、积分、排名、手环和余额",
    touchToBegin: "点击卡片开始",
    sessionClears: "返回首页时会清除本次会话数据",
    offlineTitle: "会员管理端网络连接问题",
    offlineRecovery: "连接恢复后可从首页重新开始办理。",
    operatorEyebrow: "LED GAME · 店员启动设置",
    operatorTitle: "自助注册端启动设置",
    operatorDescription: "此页面只供店员使用。顾客流程会在独立的全屏窗口中运行。",
    operatorHost: "会员管理端 IP / 主机名",
    operatorHostPlaceholder: "例如 192.168.1.10",
    operatorPort: "端口",
    operatorSave: "保存配置",
    operatorTest: "测试连接",
    operatorLaunch: "启动自助注册",
    operatorExitHint: "顾客窗口运行时，双击左侧边缘并输入店员密码即可返回本设置页。",
    staffExitEyebrow: "仅限店员",
    staffExitTitle: "关闭自助注册端",
    staffExitDescription: "请输入店员密码以返回启动设置页面。",
    staffExitPasswordLabel: "店员密码",
    staffExitPasswordPlaceholder: "请输入密码",
    staffExitCancel: "取消",
    staffExitConfirm: "确认关闭",
    staffExitInvalid: "密码错误，请重试。",
    scanStart: "开始刷手环",
    scanEyebrow: "手环读卡器",
    scanTitle: "请刷手环",
    scanDescription: "请将手环贴近读卡器，识别成功后此提示会自动关闭。",
    scanSubmittingDescription: "正在校验并绑定手环，请稍候…",
    scanWaiting: "等待读卡器输入…",
    scanConnecting: "正在连接会员管理端…",
    scanCancel: "取消刷手环",
  },
  "es-ES": home("Idioma", "Elegir idioma", "Autoservicio", "Bienvenido a la estación de jugadores", "¿Listo para", "iluminar", "la zona de juego?", "Activa tu pulsera en unos sencillos pasos.", "Activar pulsera", "Consultar jugador"),
  "pt-PT": home("Idioma", "Escolher idioma", "Autosserviço", "Bem-vindo ao posto do jogador", "Pronto para", "iluminar", "a zona de jogo?", "Ative a pulseira em poucos passos.", "Ativar pulseira", "Consultar jogador"),
  "fr-FR": home("Langue", "Choisir la langue", "Libre-service", "Bienvenue à la borne joueur", "Prêt à", "illuminer", "l’espace de jeu ?", "Activez votre bracelet en quelques étapes.", "Activer le bracelet", "Infos joueur"),
  "de-DE": home("Sprache", "Sprache wählen", "Selbstbedienung", "Willkommen an der Spielerstation", "Bereit, die", "Spielfläche", "zum Leuchten zu bringen?", "Aktiviere dein Armband in wenigen Schritten.", "Armband aktivieren", "Spielerinfo"),
  "pl-PL": home("Język", "Wybierz język", "Samoobsługa", "Witamy w stacji gracza", "Gotowi, by", "rozświetlić", "strefę gry?", "Aktywuj opaskę w kilku krokach.", "Aktywuj opaskę", "Informacje gracza"),
  "ru-RU": home("Язык", "Выберите язык", "Самообслуживание", "Добро пожаловать на станцию игрока", "Готовы", "зажечь", "игровую площадку?", "Активируйте браслет за несколько шагов.", "Активировать браслет", "Данные игрока"),
  "vi-VN": home("Ngôn ngữ", "Chọn ngôn ngữ", "Tự phục vụ", "Chào mừng đến trạm người chơi", "Sẵn sàng", "thắp sáng", "khu trò chơi?", "Kích hoạt vòng tay chỉ trong vài bước.", "Kích hoạt vòng tay", "Thông tin người chơi"),
  "it-IT": home("Lingua", "Scegli lingua", "Self-service", "Benvenuto alla postazione giocatore", "Pronto ad", "illuminare", "l’area di gioco?", "Attiva il braccialetto in pochi passaggi.", "Attiva braccialetto", "Info giocatore"),
  "cs-CZ": home("Jazyk", "Zvolit jazyk", "Samoobsluha", "Vítejte u stanice hráče", "Připraveni", "rozsvítit", "herní plochu?", "Aktivujte náramek v několika krocích.", "Aktivovat náramek", "Informace hráče"),
  "ko-KR": home("언어", "언어 선택", "셀프 서비스", "플레이어 스테이션에 오신 것을 환영합니다", "게임 공간을", "빛낼", "준비가 되셨나요?", "몇 단계만으로 손목밴드를 활성화하세요.", "손목밴드 활성화", "플레이어 정보"),
  "ro-RO": home("Limbă", "Alege limba", "Autoservire", "Bun venit la stația jucătorului", "Gata să", "luminezi", "zona de joc?", "Activează brățara în câțiva pași.", "Activează brățara", "Informații jucător"),
  "ar-SA": home("اللغة", "اختر اللغة", "الخدمة الذاتية", "مرحبًا بك في محطة اللاعب", "هل أنت مستعد", "لإضاءة", "ساحة اللعب؟", "فعّل سوارك في بضع خطوات بسيطة.", "تفعيل السوار", "معلومات اللاعب"),
} satisfies AuthoredCatalogs<typeof registrationKioskBaseCatalog>;

Object.assign(registrationKioskAuthoredCatalogs["zh-CN"], {
  offlineTitle: "会员管理端网络连接问题",
  settings: "设置",
  settingsTitle: "自助端设置",
  settingsDescription: "配置各流程无操作时自动返回首页的等待时间。",
  settingsSave: "保存设置",
  settingsCancel: "取消",
  settingsValidation: "请输入 10 到 600 秒之间的整数。",
  timeoutActivation: "激活与注册",
  timeoutWristband: "手环刷卡",
  timeoutSuccess: "完成页面",
  timeoutPlayerInfo: "会员信息查询",
  countdownRemaining: "将在 {seconds} 秒后返回首页",
  playerInfoModePhone: "手机号",
  playerInfoModeWristband: "手环",
  playerInfoPhonePlaceholder: "点击输入手机号",
  playerInfoWristbandPlaceholder: "点击输入手环 UID",
  playerInfoScan: "刷手环查询",
  playerInfoScanTitle: "请刷手环查询会员",
  playerInfoScanDescription: "请将手环靠近读卡器，仅查询会员信息，不会激活或绑定手环。",
  playerInfoScanCancel: "取消查询",
  playerInfoRecordEyebrow: "会员记录 · 实时数据",
  secondsShort: "秒",
  offlineMessage: "会员管理端网络连接出现问题，请检查网络连接。",
  avatarCameraLabel: "设备摄像头",
  avatarCameraOptional: "使用内置或 USB 摄像头，可选功能。",
  avatarCameraEyebrow: "设备摄像头",
  avatarCameraTitle: "拍摄会员头像",
  avatarCameraDescription: "照片只会在本次注册提交期间暂存。",
  avatarCameraSelect: "摄像头",
  avatarCameraLoading: "正在打开摄像头…",
  avatarCameraGuide: "请将脸部置于取景框内",
  avatarCameraCancel: "取消",
  avatarCameraRetake: "重拍",
  avatarCameraRetry: "重试摄像头",
  avatarCameraCapture: "拍照",
  avatarCameraConfirm: "使用照片",
  avatarCameraPhotoReady: "已拍摄照片",
  avatarCameraPhotoDescription: "照片已准备提交",
  avatarCameraUnsupported: "此设备不支持摄像头，请检查 Windows 摄像头设置。",
  avatarCameraPermissionDenied: "摄像头权限被拒绝，请在 Windows 隐私设置中允许本应用访问摄像头。",
  avatarCameraNoCamera: "未发现可用摄像头，请检查摄像头连接或驱动。",
  avatarCameraBusy: "摄像头正在被其他程序使用，请关闭其他占用摄像头的程序后重试。",
  avatarCameraDisconnected: "摄像头连接已中断，请检查设备后重试。",
  avatarCameraCaptureFailed: "照片处理失败，请重新拍摄或改用头像库。",
});

export const registrationKioskCatalogs = createCompleteCatalogs(
  registrationKioskBaseCatalog,
  applyQueuedTranslations(
    registrationKioskBaseCatalog,
    registrationKioskAuthoredCatalogs,
    persistedTranslations.applications.registrationKiosk.targets,
  ),
);

export function registrationKioskMessage(locale: PlatformLocale, key: RegistrationKioskMessageKey): string {
  return registrationKioskCatalogs[locale][key];
}
